import { Festival } from '../types/festival';

export type RegionArea = {
  region: string;
  districts: string[];
};

/** 지역 상세 검색에서 사용하는 시·도 / 세부 지역 목록 */
export const REGION_AREAS: RegionArea[] = [
  {
    region: '서울',
    districts: ['강남구', '홍대/신촌', '종로/중구', '송파/강동', '성수/여의도'],
  },
  {
    region: '경기',
    districts: ['수원', '가평', '고양/파주', '용인'],
  },
  {
    region: '인천',
    districts: ['중구', '연수구', '강화군'],
  },
  {
    region: '강원',
    districts: ['강릉', '평창', '속초/양양'],
  },
  {
    region: '제주',
    districts: ['제주시', '서귀포시'],
  },
  {
    region: '부산',
    districts: ['해운대구', '중구', '기장군'],
  },
];

/** 관광 데이터 API 연동 전까지 사용하는 임시 목록 */
export const FESTIVALS: Festival[] = [
  {
    id: 'fest-01',
    title: '강남 페스티벌',
    region: '서울',
    district: '강남구',
    startDate: '2026-10-02',
    endDate: '2026-10-05',
    tags: ['무료입장'],
  },
  {
    id: 'fest-02',
    title: '신촌 물총축제',
    region: '서울',
    district: '홍대/신촌',
    startDate: '2026-07-25',
    endDate: '2026-07-26',
    tags: ['체험행사'],
  },
  {
    id: 'fest-03',
    title: '서울등축제',
    region: '서울',
    district: '종로/중구',
    startDate: '2026-11-06',
    endDate: '2026-11-22',
    tags: ['무료입장', '야간행사'],
  },
  {
    id: 'fest-04',
    title: '한강 몽땅 여름축제',
    region: '서울',
    district: '성수/여의도',
    startDate: '2026-07-17',
    endDate: '2026-08-16',
    tags: ['무료입장'],
  },
  {
    id: 'fest-05',
    title: '올림픽공원 재즈 피크닉',
    region: '서울',
    district: '송파/강동',
    startDate: '2026-09-12',
    endDate: '2026-09-13',
    tags: ['공연'],
  },
  {
    id: 'fest-06',
    title: '수원 화성문화제',
    region: '경기',
    district: '수원',
    startDate: '2026-10-08',
    endDate: '2026-10-11',
    tags: ['전통문화'],
  },
  {
    id: 'fest-07',
    title: '자라섬 재즈 페스티벌',
    region: '경기',
    district: '가평',
    startDate: '2026-10-16',
    endDate: '2026-10-18',
    tags: ['공연'],
  },
  {
    id: 'fest-08',
    title: '파주 북소리 축제',
    region: '경기',
    district: '고양/파주',
    startDate: '2026-09-18',
    endDate: '2026-09-20',
    tags: ['무료입장', '체험행사'],
  },
  {
    id: 'fest-09',
    title: '인천 개항장 문화재 야행',
    region: '인천',
    district: '중구',
    startDate: '2026-08-21',
    endDate: '2026-08-23',
    tags: ['야간행사', '무료입장'],
  },
  {
    id: 'fest-10',
    title: '송도 맥주축제',
    region: '인천',
    district: '연수구',
    startDate: '2026-08-07',
    endDate: '2026-08-09',
    tags: ['먹거리'],
  },
  {
    id: 'fest-11',
    title: '강화 고인돌 축제',
    region: '인천',
    district: '강화군',
    startDate: '2026-10-10',
    endDate: '2026-10-12',
    tags: ['전통문화'],
  },
  {
    id: 'fest-12',
    title: '강릉 커피축제',
    region: '강원',
    district: '강릉',
    startDate: '2026-10-02',
    endDate: '2026-10-05',
    tags: ['먹거리', '체험행사'],
  },
  {
    id: 'fest-13',
    title: '대관령 음악제',
    region: '강원',
    district: '평창',
    startDate: '2026-07-24',
    endDate: '2026-08-08',
    tags: ['공연'],
  },
  {
    id: 'fest-14',
    title: '양양 서핑 페스타',
    region: '강원',
    district: '속초/양양',
    startDate: '2026-08-14',
    endDate: '2026-08-16',
    tags: ['체험행사'],
  },
  {
    id: 'fest-15',
    title: '제주 들불축제',
    region: '제주',
    district: '제주시',
    startDate: '2026-03-05',
    endDate: '2026-03-08',
    tags: ['무료입장'],
  },
  {
    id: 'fest-16',
    title: '서귀포 유채꽃 걷기대회',
    region: '제주',
    district: '서귀포시',
    startDate: '2026-04-11',
    endDate: '2026-04-12',
    tags: ['무료입장', '체험행사'],
  },
  {
    id: 'fest-17',
    title: '부산 국제영화제',
    region: '부산',
    district: '해운대구',
    startDate: '2026-10-01',
    endDate: '2026-10-10',
    tags: ['공연'],
  },
  {
    id: 'fest-18',
    title: '부산 자갈치축제',
    region: '부산',
    district: '중구',
    startDate: '2026-10-15',
    endDate: '2026-10-18',
    tags: ['먹거리', '무료입장'],
  },
  {
    id: 'fest-19',
    title: '기장 멸치축제',
    region: '부산',
    district: '기장군',
    startDate: '2026-04-24',
    endDate: '2026-04-26',
    tags: ['먹거리'],
  },
];
